language: node_js
node_js:
  - 'lts/*'
  - 'node'
cache: yarn
before_install:
  - yarn global add codecov

jobs:
  include:
    - stage: Build
      script:
        - yarn build

    - stage: Integration and Unit tests
      script:
        - yarn test

    - stage: Visual regression tests
      if: type = pull_request
      script:
        - yarn test:percy

after_success:
  - codecov
