export default [
  {
    title: 'Getting Started',
    icon: 'rocket',
    href: '/getting-started',
  },
  {
    title: 'About',
    icon: 'chatFilled',
    href: '/about',
  },
  {
    title: 'Design Guidelines',
    icon: 'penTool',
    href: '/design-guidelines',
    children: [
      { href: '/design-guidelines/accessibility', title: 'Accessibility' },
      { href: '/design-guidelines/color', title: 'Color' },
      { href: '/design-guidelines/grid', title: 'Grid' },
      { href: '/design-guidelines/iconography', title: 'Iconography' },
      { href: '/design-guidelines/illustrations', title: 'Illustrations' },
      { href: '/design-guidelines/typography', title: 'Typography' },
    ],
  },
  {
    title: 'Usage',
    icon: 'code',
    href: '/usage',
    children: [
      { href: '/usage/styles', title: 'Styles' },
      { href: '/usage/theme', title: 'Theme' },
      { href: '/usage/i18n', title: 'Internationalization' },
    ],
  },
  {
    title: 'Components',
    icon: 'bricksFilled',
    href: '/components',
    children: [
      { href: '/components/accordion', title: 'Accordion' },
      { href: '/components/alert', title: 'Alert' },
      { href: '/components/breadcrumb', title: 'Breadcrumb' },
      { href: '/components/button', title: 'Button' },
      { href: '/components/cards', title: 'Cards' },
      { href: '/components/checkbox', title: 'Checkbox' },
      { href: '/components/content-switch', title: 'Content Switch' },
      { href: '/components/date-picker', title: 'Date Picker' },
      { href: '/components/dropdown', title: 'Dropdown' },
      { href: '/components/file-uploader', title: 'File Uploader' },
      { href: '/components/form', title: 'Form' },
      { href: '/components/link', title: 'Link' },
      { href: '/components/modal', title: 'Modal' },
      { href: '/components/multi-select', title: 'Multi Select' },
      { href: '/components/paginator', title: 'Paginator' },
      { href: '/components/radio-button', title: 'Radio Button' },
      { href: '/components/search', title: 'Search' },
      { href: '/components/select', title: 'Select' },
      { href: '/components/switch', title: 'Switch' },
      { href: '/components/table', title: 'Table' },
      { href: '/components/tabs', title: 'Tabs' },
      { href: '/components/tag', title: 'Tag' },
      { href: '/components/text-input', title: 'Text Input' },
      { href: '/components/toast', title: 'Toast' },
      { href: '/components/tooltip', title: 'Tooltip' },
      { href: '/components/wizard', title: 'Wizard' },
    ],
  },
  {
    title: 'Resources',
    icon: 'archiveFilled',
    href: '/resources',
  },
  {
    title: 'Storybook',
    icon: 'list',
    target: '_blank',
    href: 'https://bold.bridge.ufsc.br/storybook',
  },
]
