export * from './Circle'
export * from './Square'
export * from './Rectangle'
export * from './Triangle'
export * from './Diamond'
export * from './Cross'
export * from './Star'
export * from './Happy'
